## Descarga de datos del dataset Forbes2000 (paquete HSAUR) mediante get_rdataset()
Ranking de empresas categorizadas por sector, y con información de país, ventas, beneficios, recursos y valor de mercado.

In [2]:
import numpy as np
import statsmodels.api as sm

dataset_forbes = sm.datasets.get_rdataset("Forbes2000", "HSAUR")
data_forbes = dataset_forbes.data
data_forbes.head(10)

,rank,name,country,category,sales,profits,assets,marketvalue
0,1,Citigroup,United States,Banking,94.71,17.85,1264.03,255.30
1,2,General Electric,United States,Conglomerates,134.19,15.59,626.93,328.54
2,3,American Intl Group,United States,Insurance,76.66,6.46,647.66,194.87
3,4,ExxonMobil,United States,Oil & gas operations,222.88,20.96,166.99,277.02
4,5,BP,United Kingdom,Oil & gas operations,232.57,10.27,177.57,173.54
5,6,Bank of America,United States,Banking,49.01,10.81,736.45,117.55
6,7,HSBC Group,United Kingdom,Banking,44.33,6.66,757.60,177.96
7,8,Toyota Motor,Japan,Consumer durables,135.82,7.99,171.71,115.40
8,9,Fannie Mae,United States,Diversified financials,53.13,6.48,1019.17,76.84
9,10,Wal-Mart Stores,United States,Retailing,256.33,9.05,104.91,243.74

## Selección de empresas que incluyen "elect" (sin tener en cuenta mayúsculas)

In [5]:
data_elect = data_forbes[data_forbes.name.str.contains("elect", case = False)]
data_elect

,rank,name,country,category,sales,profits,assets,marketvalue
1,2,General Electric,United States,Conglomerates,134.19,15.59,626.93,328.54
44,45,Samsung Electronics,South Korea,Semiconductors,50.22,5.95,54.58,72.72
71,72,Tokyo Electric Power,Japan,Utilities,41.62,1.40,116.68,30.63
151,152,Korea Electric Power,South Korea,Utilities,18.01,2.57,58.38,11.84
156,157,Kansai Electric Power,Japan,Utilities,22.12,0.68,60.52,17.56
170,171,Chubu Electric Power,Japan,Utilities,18.41,0.90,52.08,15.59
219,220,Emerson Electric,United States,Conglomerates,14.33,1.12,15.71,26.88
280,281,Tohoku Electric Power,Japan,Utilities,13.48,0.52,34.49,8.67
284,285,Kyushu Electric Power,Japan,Utilities,12.02,0.54,34.69,8.48
322,323,Schneider Electric,France,Capital goods,11.04,0.54,14.37,15.39
414,415,Matsushita Electric Indl,Japan,Consumer durables,62.62,-0.16,60.46,33.02
424,425,STMicroelectronics,Switzerland,Semiconductors,7.98,0.28,11.98,24.11
433,434,Electrolux Group,Sweden,Consumer durables,15.34,0.59,9.50,6.93
439,440,Chugoku Electric Power,Japan,Utilities,8.54,0.37,23.36,6.41
567,568,American Electric,United States,Utilities,15.58,-0.16,36.08,13.21
585,586,Mitsubishi Electric,Japan,Capital goods,30.79,-0.10,26.24,10.28
621,622,Hughes Electronics,United States,Media,10.12,-0.30,18.95,23.56
634,635,Matsushita Electric Works,Japan,Capital goods,11.26,0.19,9.37,6.54
641,642,Sanyo Electric,Japan,Consumer durables,19.24,-0.62,21.65,9.43
646,647,Electronic Data Sys,United States,Software & services,21.48,-0.27,18.28,9.98
727,728,Shikoku Electric Power,Japan,Utilities,4.95,0.22,11.96,4.65
786,787,Sumitomo Electric,Japan,Capital goods,12.60,-0.17,13.46,6.38
798,799,Hokkaido Electric Power,Japan,Utilities,4.39,0.22,11.85,3.76
810,811,Hongkong Electric,Hong Kong/China,Utilities,1.49,0.88,7.26,9.04
829,830,United Microelectronics,Taiwan,Semiconductors,2.18,0.20,9.29,14.66
856,857,Hokuriku Electric Power,Japan,Utilities,4.08,0.18,13.09,3.74
863,864,Electronic Arts,United States,Software & services,2.82,0.50,3.34,13.28
1078,1079,Odakyu Electric Railway,Japan,Transportation,5.47,0.07,10.69,3.72
1155,1156,Tokyo Electron,Japan,Semiconductors,3.90,-0.35,4.36,11.71
1183,1184,Verbund-Austrian Electric,Austria,Utilities,2.18,0.16,7.27,4.28
1198,1199,Compal Electronics,Taiwan,Technology hardware & equipment,3.38,0.23,2.72,4.07
1250,1251,Furukawa Electric,Japan,Capital goods,6.01,-0.96,9.91,2.52
1273,1274,Keio Electric Railway,Japan,Transportation,3.55,0.13,4.40,3.49
1296,1297,Kesa Electricals,United Kingdom,Retailing,5.64,0.16,2.81,2.72
1332,1333,Alps Electric,Japan,Business services & supplies,5.09,0.15,4.00,2.30
1336,1337,Funai Electric,Japan,Consumer durables,2.80,0.16,1.60,4.70
1346,1347,Arrow Electronics,United States,Technology hardware & equipment,8.09,0.01,5.04,2.67
1394,1395,Fuji Electric,Japan,Capital goods,7.04,0.03,7.73,1.55
1395,1396,Thermo Electron,United States,Health care equipment & services,2.10,0.20,3.39,4.63
1460,1461,Nippon Electric Glass,Japan,Business services & supplies,2.78,0.12,4.15,3.25
1462,1463,SEM-Samsung Electro,South Korea,Technology hardware & equipment,3.29,0.18,3.00,2.74
1467,1468,Oki Electric Industry,Japan,Business services & supplies,4.95,-0.06,5.05,2.69
1580,1581,Keihin Electric Express,Japan,Transportation,2.65,0.07,6.11,3.22
1581,1582,Johnson Electric Holdings,Hong Kong/China,Capital goods,0.96,0.15,0.85,4.73
1820,1821,Chi Mei Optoelectronics,Taiwan,Technology hardware & equipment,1.72,0.13,2.62,3.68
1835,1836,Hawaiian Electric,United States,Utilities,1.76,0.10,9.03,1.94
1841,1842,Guangdong Electric Power,China,Utilities,0.67,0.14,1.43,3.39
1967,1968,Hirose Electric,Japan,Technology hardware & equipment,0.57,0.10,1.63,4.29
1988,1989,Stanley Electric,Japan,Consumer durables,2.00,0.11,1.82,3.23
1996,1997,Yokogawa Electric,Japan,Business services & supplies,2.78,-0.22,2.96,3.29

## Obtención del valor de mercado de las empresas japonesas y estadounidenses
Utilizando como índice el país y la categoría

In [4]:
data_elect_indexed = data_elect.set_index(['country', 'category'])
data_elect_indexed.sort_index(inplace=True)
data_elect_indexed.head(10)

                                              rank                       name  \
country         category
Austria         Utilities                     1184  Verbund-Austrian Electric
China           Utilities                     1842   Guangdong Electric Power
France          Capital goods                  323         Schneider Electric
Hong Kong/China Capital goods                 1582  Johnson Electric Holdings
                Utilities                      811          Hongkong Electric
Japan           Business services & supplies  1333              Alps Electric
                Business services & supplies  1461      Nippon Electric Glass
                Business services & supplies  1468      Oki Electric Industry
                Business services & supplies  1997          Yokogawa Electric
                Capital goods                  586        Mitsubishi Electric

                                              sales  profits  assets  \
country         category
Austria         Utilities                      2.18     0.16    7.27
China           Utilities                      0.67     0.14    1.43
France          Capital goods                 11.04     0.54   14.37
Hong Kong/China Capital goods                  0.96     0.15    0.85
                Utilities                      1.49     0.88    7.26
Japan           Business services & supplies   5.09     0.15    4.00
                Business services & supplies   2.78     0.12    4.15
                Business services & supplies   4.95    -0.06    5.05
                Business services & supplies   2.78    -0.22    2.96
                Capital goods                 30.79    -0.10   26.24

                                              marketvalue
country         category
Austria         Utilities                            4.28
China           Utilities                            3.39
France          Capital goods                       15.39
Hong Kong/China Capital goods                        4.73
                Utilities                            9.04
Japan           Business services & supplies         2.30
                Business services & supplies         3.25
                Business services & supplies         2.69
                Business services & supplies         3.29
                Capital goods                       10.28

In [5]:
data_elect_indexed[[country in ['Japan','United States'] for country,category in data_elect_indexed.index ]][['name','marketvalue']]

                                                                     name  \
country       category
Japan         Business services & supplies                  Alps Electric
              Business services & supplies          Nippon Electric Glass
              Business services & supplies          Oki Electric Industry
              Business services & supplies              Yokogawa Electric
              Capital goods                           Mitsubishi Electric
              Capital goods                     Matsushita Electric Works
              Capital goods                             Sumitomo Electric
              Capital goods                             Furukawa Electric
              Capital goods                                 Fuji Electric
              Consumer durables                  Matsushita Electric Indl
              Consumer durables                            Sanyo Electric
              Consumer durables                            Funai Electric
              Consumer durables                          Stanley Electric
              Semiconductors                               Tokyo Electron
              Technology hardware & equipment             Hirose Electric
              Transportation                      Odakyu Electric Railway
              Transportation                        Keio Electric Railway
              Transportation                      Keihin Electric Express
              Utilities                              Tokyo Electric Power
              Utilities                             Kansai Electric Power
              Utilities                              Chubu Electric Power
              Utilities                             Tohoku Electric Power
              Utilities                             Kyushu Electric Power
              Utilities                            Chugoku Electric Power
              Utilities                            Shikoku Electric Power
              Utilities                           Hokkaido Electric Power
              Utilities                           Hokuriku Electric Power
United States Conglomerates                              General Electric
              Conglomerates                              Emerson Electric
              Health care equipment & services            Thermo Electron
              Media                                    Hughes Electronics
              Software & services                     Electronic Data Sys
              Software & services                         Electronic Arts
              Technology hardware & equipment           Arrow Electronics
              Utilities                                 American Electric
              Utilities                                 Hawaiian Electric

                                                marketvalue
country       category
Japan         Business services & supplies             2.30
              Business services & supplies             3.25
              Business services & supplies             2.69
              Business services & supplies             3.29
              Capital goods                           10.28
              Capital goods                            6.54
              Capital goods                            6.38
              Capital goods                            2.52
              Capital goods                            1.55
              Consumer durables                       33.02
              Consumer durables                        9.43
              Consumer durables                        4.70
              Consumer durables                        3.23
              Semiconductors                          11.71
              Technology hardware & equipment          4.29
              Transportation                           3.72
              Transportation                           3.49
              Transportation                           3.22
              Utilities                               30.63
              Utilities                               17.56
              Utilities                               15.59
              Utilities                                8.67
              Utilities                                8.48
              Utilities                                6.41
              Utilities                                4.65
              Utilities                                3.76
              Utilities                                3.74
United States Conglomerates                          328.54
              Conglomerates                           26.88
              Health care equipment & services         4.63
              Media                                   23.56
              Software & services                      9.98
              Software & services                     13.28
              Technology hardware & equipment          2.67
              Utilities                               13.21
              Utilities                                1.94

## Obtención del país donde el sector de utilities tiene mayor valor de mercado medio en sus empresas

In [6]:
utilities = data_elect_indexed[[category == 'Utilities' for country,category in data_elect_indexed.index ]]
marketvalue_countries  = utilities.groupby(level = 0).mean()[['marketvalue']]
marketvalue_countries.sort('marketvalue')

C:\Users\Ainhoa\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  app.launch_new_instance()

                 marketvalue
country
China               3.390000
Austria             4.280000
United States       7.575000
Hong Kong/China     9.040000
Japan              11.054444
South Korea        11.840000

El país en el que las empresas tienen un mayor valor medio de mercado es South Korea.

## Volviendo al dataset original, obtención de las empresas españolas

In [9]:
data_forbes[data_forbes.country == 'Spain'][['name']]

                           name
38      Banco Santander Central
56    BBVA-Banco Bilbao Vizcaya
108                  Repsol-YPF
114                Endesa Group
188                   Iberdrola
378       Banco Popular Espaqol
408                  Telefsnica
462             Gas Natural SDG
472                     Altadis
529                Unisn Fenosa
532                       Cepsa
605             Grupo Ferrovial
734                   FCC Group
762                     Inditex
787           Banco de Sabadell
876                   ACS Group
951          Corporation Mapfre
1035                    Acciona
1058                  Bankinter
1059   Abertis Infraestructuras
1074                     Iberia
1426      Amadeus Global Travel
1435         Sacyr-Vallehermoso
1493                   Acerinox
1623                     Enagas
1892               Banco Pastor
1897     Red Eectrica de Espaqa
1931                     Gamesa
1992                  Sogecable

## Indexación del dataframe por profits y obtención de nombres y rangos de las que tengan beneficio nulo o negativo.
Nota: Intentar indexar de manera mixta con números (filas) y etiquetas (columnas)

In [7]:
empresas_espanolas = data_forbes[data_forbes.country == 'Spain']
empresas_espanolas_indexadas = empresas_espanolas.set_index('profits')
empresas_espanolas_indexadas.sort_index(inplace=True)
empresas_espanolas_indexadas.ix[:0,['name','assets', 'rank']]

               name  assets  rank
profits
-5.86    Telefsnica   60.65   409
-0.06     Sogecable    1.53  1993